version: '3'
services:
  mantisbt:
    container_name: mantis
    build:
      context: ./build
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    volumes:
      - ./files:/opt/files
      - ./config/config_defaults_inc.php:/var/www/html/config_defaults_inc.php
      - ./config/strings_portuguese_brazil.txt:/var/www/html/lang/strings_portuguese_brazil.txt
    links:
      - mysql
    restart: always
  mysql:
    container_name: mantis_mariadb
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3300:3306"
    restart: always
